env:
  global:
    - CC_TEST_REPORTER_ID=efa5aa59a604b59fd9ea9e4280cb9a81f0fc6c058212e81f951af54c7f19d46e
language: node_js
node_js:
  - "8"
  - "6"
  - "10"
os:
  - linux
  - osx
cache:
  directories:
  - node_modules # NPM packages
before_script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar -o phpcbf
  - ls -la
  - sudo chmod a+x ./phpcbf || true
  - which phpcbf || true
  - ls -la
  - sudo mv ./phpcbf /usr/local/bin/phpcbf
  - which phpcbf || true
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter;
    else
      echo Error:TRAVIS_OS_NAME && exit 1;
    fi
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - which phpcbf
  - phpcbf --version
  - npm run build
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    on_success: never
    on_failure: change
